version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./src:/root/src
    networks:
      - app-network
    restart: always
    depends_on:
      - db_mysql
  db_mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: beajzoq1yzlj5drogqzl
      MYSQL_USER: ucet1kqkhzpz25to
      MYSQL_PASSWORD: Ktsk8XnHeoVkYA0ZI5aM
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - db_mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: always
networks:
  app-network:
    driver: bridge
volumes:
  db_mysql-data: