# Configuración del servidor
server:
  port: ${PORT:8083} # Render asignará el puerto o usará 8080 por defecto

# Configuración de la base de datos
spring:
  datasource:
    url: ${URL}
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      minimum-idle: 1
      max-lifetime: 1800000
      idle-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

# Configuración de Springdoc (Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
