server:
  port: ${PORT:8080}
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    hikari:
      connection-timeout: 30000

# Configuración de las APIs externas
external:
  api1:
    url: https://api1.prod.com
    key: prod-api-key-1
  api2:
    url: https://api2.prod.com
    key: prod-api-key-2
  api3:
    url: https://api3.prod.com
    key: prod-api-key-3

# Configuración de logs para producción
logging:
  level:
    root: info
    org.springframework.web: warn
  file:
    name: logs/application-prod.log